### ISSUE TITLE
[Suggestion] Optionnal support for Redstone Armory

### ISSUE THREAD

**Issue by HanatakeYurii** [Tonius/SimplyJetpacks#100]
Hi,

First, I love your mods (also using E-mobile, the sounds make me laugh every time)
That said, I play with many mods, one of them is Redstone Armory that add a higher tier to all tools/weapons/armor including the Fluxed-Infused Chestplate (needed for the jetplate) that can be crafted into a Gelid Enderium Chestplate (a bit more storage and a enderium-green texture).

Since I though a bit ridiculous to be full greened-armor except the jetplate, I would suggest to add a green jetplate that use the Gelid Enderium Chestplate and that have a bit more storage and protection.

What do you think?

**Comment by Tonius** [comment]
I don't think another tier is really necessary. The JetPlate is already very powerful (maybe a bit too powerful), and can be configured to be even more so.

However, I am considering a simple visual upgrade to make it fit with the other RArm armor pieces.

**Comment by HanatakeYurii** [comment]
Ok, I really understand what you think, JetPlate is already really good.

Thanks for considering a visual upgrade :)

**Comment by Badcholo** [comment]
I'm for a visual upgrade. it's way better than RArms armor and can fly, good enough. It will now just match.

**Comment by KaneHart** [comment]
I also like to see this added. I like to see the 200 or so mechanic rf for damage as well. I think it matches visually better but also a version to work with that mod as well since most people use the arsenal as like tier 2 and Armory as tier 3.
