### ISSUE TITLE
[Suggestion] Make forward thrust work with double tap forward, like sprinting

### ISSUE THREAD

**Issue by BBoldt** [Tonius/SimplyJetpacks#102]
shhhhh

**Comment by Tonius** [comment]
Have you tried the sprint key? It can be used while in the air. By default it's bound to Ctrl, but FMP and possibly others usually overwrite it.

**Comment by BBoldt** [comment]
Changed suggestion to making it work with the "double tap W" method of sprinting. Not once have I used the actual sprint key.

**Comment by BBoldt** [comment]
\o/

Thanks @Tonius

**Comment by nabijaczleweli** [comment]
Praise the @Tonius!
