### ISSUE TITLE
Fuel consumption increasing over time

### ISSUE THREAD

**Issue by Zyx-2000** [Tonius/SimplyJetpacks#111]
I like this mod, and I think the jetpacks are well-balanced for some use cases. Unfortunately, in some situations they are extremely overpowered, and causes other problems as well.

A big problem in my opinion is that jetpacks can be used as a way of travelling long distances. They are completely overpowered for that purpose, and makes all other ways useless. It requires 0 setup (unlike for example minecart networks), can be used to travel to any given location, and mainly, it is a lot faster than all other methods. It also causes the server to lag, because chunks are loaded in too quickly.

The problem would be solved if fuel consumption was to increase over time. Then, jetpacks would not be overpowered for travelling, but still useful for all other purposes. When used, jetpacks should "heat up", more heat increasing fuel consumption. When not used, "heat" will go down over time. It should be added as a config option, since everyone wouldn't like this addition.

**Comment by nabijaczleweli** [comment]
"A big problem in my opinion is that jetpacks can be used as a way of travelling long distances." (sic)
Hey, guess, what! This is ***EXACTLY*** what jetpacks are *for*!

**Comment by medsal15** [comment]
You don't need a setup because you need RF to go. RF aren't naturally generated.

**Comment by Badcholo** [comment]
A fix for the lag is to reduce the speed a jetpack can move while flying. however you'll have to do that to every tier to make it balanced.

**Comment by Badcholo** [comment]
Stargates, Teleporters, /home set, plugins for warp stations. all of these can be included in a Server to minimize players flying everywhere with jetpacks. but if someone just wanted to lag up a server and cause lag, yes they can do that with jetpacks. you'll need to tweak chucks loading / unloading and get more ram to cover the loaded chuncks until they can get unloaded safely without causing massive lag.

**Comment by mikeloeven** [comment]
This request makes no sense fuel usage is a constant rate the only thing that would actually affect the rate of fuel consumption would be the players weight which to the best of my knowledge is not calculated

**Comment by Badcholo** [comment]
This request is pointless. Don't install jetpacks on your server if your server can't handle them.

**Comment by Tonius** [comment]
Jetpacks being overpowered for you seems to be the real issue here. Their speed and other properties can be changed/nerfed in the config, or disabled completely through MineTweaker.
