### ISSUE TITLE
[1.5.1] Jetpack in Anvil crashes game - Updating Screen Events

### ISSUE THREAD

**Issue by DragonGodGrapha** [Tonius/SimplyJetpacks#116]
http://pastebin.com/rtpXizdR

Crash when trying to add enchantments via anvil.

**Comment by Tonius** [comment]
Did the jetpack have the Fuel Efficiency enchant on it? And was said enchantment disabled in the config afterwards?

This would leave an invalid enchantment on the item, and the Anvil doesn't like that. Unfortunately, there's no way for me to check for this.

If this is still an issue for you, deleting the jetpack and spawning in a new one should fix it.
