### ISSUE TITLE
Can't craft a leadstone thruster 

### ISSUE THREAD

**Issue by danielroy** [Tonius/SimplyJetpacks#117]
I've been trying to craft a leadstone thruster for Simply Jetpacks, but it never works.  The recipe is completely different than what I've seen online, but I have the required items.  When I try to craft the thruster, it appears but cannot be added to my inventory.  I've created a short clip to show you what I mean.  I'm using SimplyJetpacks-MC1.7.10-1.5.1.jar.  Could this be mod related or something misconfigured in my configs?

The clip: http://quick.as/9GRGfP76y

![image](https://cloud.githubusercontent.com/assets/6785509/9894788/ecb6496c-5bf5-11e5-9357-5d72c0806e29.png)

**Comment by Alaberti** [comment]
What other mods do you have? Is this on a server (perhaps one with forge-essentials permissions enabled?)

**Comment by danielroy** [comment]
I'm pretty sure it was a misconfigured mod.  I cleared all my mods and started again, and now it's working without issue.  Thanks for following up.
