### ISSUE TITLE
Modular Power Armor Jetpack Addon.

### ISSUE THREAD

**Issue by Badcholo** [Tonius/SimplyJetpacks#121]
How about the ability to add a jetpack to Power Armor.
While power armor is neat, it lacks the 3d jetpacks and effect.

Suggestion: Ability to add the different tiers jetpacks to the power armor using the tinkers table removing the old way of adding a jetpack to power armor.

https://github.com/QMXTech/Numina
https://github.com/QMXTech/MachineMusePowersuits
https://github.com/QMXTech/ModularPowersuitsAddons

close it if you don't like it. thanks.

**Comment by nabijaczleweli** [comment]
:+1:

**Comment by Badcholo** [comment]
nabijaczleweli
You got a download for the BriefcaseSpeakers, I'd love to try it out. please?

**Comment by nabijaczleweli** [comment]
@Badcholo What are you asking, exactly?

**Comment by Badcholo** [comment]
I was asking if you had a download link to that mod.

**Comment by nabijaczleweli** [comment]
@Badcholo No, but you can build it yourself.
Also, this is not a place for such a discussion.

**Comment by Badcholo** [comment]
Well, i would be asking for it if i could build it myself.
I don't think it's such a big issue with what i said.
Also you don't have to be a jerk about it. All you had to say was, no.
Since this issue has been so... tainted, -_- i think ima just close it.

**Comment by nabijaczleweli** [comment]
ITT politely answering no, offering a solution and indicating improperness of "discussion"'s place == being a jerk
