### ISSUE TITLE
Flux Baubles

### ISSUE THREAD

**Issue by Yusunoha** [Tonius/SimplyJetpacks#60]
right now there's jetpacks and flux packs in Simply Jetpacks, but both need to be worn in the armor slot to be able to use them. that's fine for the jetpack, but for the flux pack I sometimes want to use different chestplates that give different effects, but still want to be able to charge my tools.

I know I could use the flux capacitors, but I rather not because they're not that great. so I was hoping if it'd be possible if there could be flux baubles in this mod aswell. they'd be similar to the flux capacitors from Thermal Expansion, but these flux baubles can be worn in the baubles window and will charge both armor and tools if they accept RF

**Comment by Tonius** [comment]
This seems to be a thing in [Redstone Armory](http://www.curse.com/mc-mods/minecraft/229339-redstone-armory) by now.

**Comment by nabijaczleweli** [comment]
lol the age of this issue
