### ISSUE TITLE
Jetplate isn't usable in Anvil

### ISSUE THREAD

**Issue by PiggyWhiskey** [Tonius/SimplyJetpacks#69]
Made full flux armour and went the Ender IO Route for the Jetplate.

Only to discover, it isn't usable in an Anvil or Auto-Anvil (MFR)

Testing shows only Enchant Table and Auto-Enchanter (MFR) work.

**Comment by Tonius** [comment]
After some investigation, I have come to the following conclusion:
MFR's Auto-Anvil works on any item that is damageable, and doesn't work with any items that aren't. This causes problems with items that have infinite durability, but also with SJ's jetpacks (stored energy does not count as damage in this case). It may very well be a balance move on MFR's part though.
@skyboy: is this intended or an oversight?

**Comment by skyboy** [comment]
@Tonius I've corrected the logic, but due to bad MCP naming it looks wrong. You will have to override `isItemTool` and return true for this to work in the next version, that method is used to determine if an item can be enchanted.

**Comment by Tonius** [comment]
ItemJetpack already does this, so that should be fine.
https://github.com/Tonius/SimplyJetpacks/blob/master/src/main/java/tonius/simplyjetpacks/item/ItemJetpack.java#L194

**Comment by Tonius** [comment]
Should be working in the latest MFR dev builds.
