### ISSUE TITLE
Config still overwrites itself with every launch

### ISSUE THREAD

**Issue by thehobojoe** [Tonius/SimplyJetpacks#75]
Pretty much all there is to say. The mod is not configurable because it resets every launch. This issue existed 6 months ago in the first release of the mod in 1.7.10, and still exists in the current release.

**Comment by Tonius** [comment]
If this issue existed for you 6 months ago, you could have submitted this earlier...

Either way, I'll have a look. Last I checked 1.7.10 configs were saving fine for me.

**Comment by Tonius** [comment]
Still working fine here. Has been working fine all along. I'm gonna need some extra info:
- A full log of your game starting up
- Which parts of the config are you trying to change?
- How are you editing the config? Using the config GUI, or by editing the files directly? And if you are editing directly, are you sure they are being saved properly?
- Are the config files set to be read-only?

Other than that, I wouldn't know what is wrong. All I know is that it's not the mod being bugged.

**Comment by technolem** [comment]
Actually, I had noticed this problem with 1.3.1, back when I was listing config bugs. Must've forgot to mention it. No other version though, 1.3.2 works just fine for me. I haven't tested 1.3.1 since then, so it may have just been a side effect of me launching and exiting minecraft to test things.

**Comment by thehobojoe** [comment]
Sorry, I wrote this report in a bad mood, was much more snarky than it should have been. I vaguely remember reporting this issue in IRC months ago, but I could be mis-remembering that. I'll take some more detailed info later today when I'm able, but I'm editing the configs the same way I edit configs for every other mod, and this is an issue I haven't seen anywhere else before - just using a text editor (sublime text), the files are saving correctly, I can save, close, and re-open them after changes and it works fine, which rules out the files being read-only. I wasn't aware of a config GUI, I'll take a look at that later too.

**Comment by thehobojoe** [comment]
I revisited this issue, the overwrite happens when the game is *closed*. It's something I haven't seen happen with any other mod configs. When the game is closed the config resets itself to whatever it was when the game was launched.

**Comment by Tonius** [comment]
Just any time the game is closed, or only when closed during gameplay?
