### ISSUE TITLE
RArm support (Enderium JetPlate)

### ISSUE THREAD

**Issue by HanFox** [Tonius/SimplyJetpacks#77]
I had already asked over on the RArm tracker for implementation (https://github.com/TehNut/RedstoneArmory/issues/10) but TehNut said he'd like to but he's unsure of implementation.

So, maybe either you can add it in to SJ or you can work with TehNut to get it implemented? It'd be nice to achieve a full Enderium set ;)

**Comment by Aedaeum** [comment]
I've been looking forward to this as well, hopefully something can be done :)

**Comment by Tonius** [comment]
What would be special about an Enderium version of the JetPlate, though, other than the skin/crafting? I'm not particularly fond of just adding a reskinned version of the same thing.

**Comment by HanFox** [comment]
Considering it's made from Resonant Ender infused metals I was thinking it could be used to teleport to areas you have marked by visiting them (quite possibly with an extra item you add i.e. a "Pin-Pointer" if you like).

The amount of pin-pointable locations would be configurable (5 points by default?) so you can't just go warping all over the map like crazy and possibly have a cooldown or something might go awry in the jetpack (damage/death/explosion/fire/random teleport location). You could also still have a % failure with much the same negative effects.

The teleporting would be at a large cost of energy relative to distance much like IC2's teleporters. It could also, like IC2's teleporters, possibly cost more the more items you're holding.

**Comment by Badcholo** [comment]
Your thinking of a different mod. This doesn't fit in with this mod at all. i don't really like the idea of a teleporter.

**Comment by Badcholo** [comment]
We do need a Jetpack for RArm, but i don't like the teleport idea or a config to remove it. Maybe it can be fire proof unlike all the other stuff that makes it so you can swim in lava with no damage, but as soon as you leave the lava you start taking fire damage.

**Comment by HanFox** [comment]
Whilst I can understand you not liking the idea, I don't see how fire proofing relates to Resonant Ender (which is what the jetplate would basically be made of).

Resonant Ender as a liquid does random teleports. So a shaped and moulded - "tamed" if you like - version of the item should relate to being able to control its base properties.

Also, the jetplates from what I recall (not played in a while), are enchantable, so you could just add the Fire Protection enchant anyway to help lava survivability.

**Comment by Badcholo** [comment]
Have you tried the pickaxe from RArm? i died like a bunch of times just trying to mine until i removed it from the config. Resonant Ender is a Tier level, not everything Ender has to teleport you. Ender Chest is storage, Ender swords are used like a magnet, The Tier Ender just means Very Awsome nice upgrades. Plus for as expensive as the crafting is why aren't these armors fire proof anyways?
Same for the boots, why do they still cause the same amount of fall damage? I'm not mad, i just think it makes sense to add these things to armor.

**Comment by HanFox** [comment]
No, not everything "Ender" needs to teleport, but the Jetplate is a transportation device. It just makes sense to me. Then again there could always be "extra" upgrades to things which might work well with the new [GUI system](https://twitter.com/ToniusMods/status/592385519897706498).

The idea of the "upgrades" would be comparable to augments in Thermal Expansion machines. Better the tier of armour more augment slots?

**Comment by Badcholo** [comment]
Well i wouldn't mind a config to disable this. I'm just not a big fan of players being able to teleport past walls like having a blink drive. I have E-mobile mod, TF2 Teleport pads. jump pads, ender io, aroma mining world, these provide enough teleport for me, plus the jetpacks top tier move so fast. ender io has several ways to teleport to specific locations. Remote Io is really nice too. so many items that are already out there for teleporting. A jetpack has a Armor function and a Movement function "fly". you said it yourself a Transportations device not a Teleportation device but i get what your saying. Possibly if you want to make it like the E-mobile phone mod that takes you to your home upon request or set multiple homes i guess. these things are very expensive for what they do. RArm seems like an expensive tier but not very useful past Redstone Arsenal. The increase in armor and uses is very minimal for the cost.

**Comment by Tonius** [comment]
I've left a comment on #100 about how I might want to handle this.

**Comment by HanFox** [comment]
Sounds good to me, :)

The only reason I ever stated anything about teleportation is because originally you didn't just want to just add a reskin/different visual version.
