### ISSUE TITLE
Suggestion: Make Jetpack explode and kill you if you try to use it while swimming in flammable fluids

### ISSUE THREAD

**Issue by Vexatos** [Tonius/SimplyJetpacks#80]
Things like BuildCraft Oil/Fuel or Forestry Ethanol are considered flammable fluids; since I assume these jetpacks produce some kind of heat, it'd be a nice feature if they would explode and kill you with a funny death message if you try to use them while swimming in such kinds of fluid.
To check whether a fluid block is flammable, there is the native method `isFlammable(IBlockAccess world, int x, int y, int z, ForgeDirection face)` on fluid blocks, so it should be rather easy to do.

**Comment by KingLemming** [comment]
Actually @Vexatos, I believe those fluids are inflammable.

**Comment by Vexatos** [comment]
@KingLemming [I checked, they are](https://github.com/BuildCraft/BuildCraft/blob/6.1.x/common/buildcraft/BuildCraftEnergy.java#L187).

**Comment by Vexatos** [comment]
@KingLemming [I checked, oil at least is by default (Config option)](https://github.com/BuildCraft/BuildCraft/blob/6.4.x/common/buildcraft/BuildCraftEnergy.java#L210).

**Comment by Vexatos** [comment]
@KingLemming You are one evil being :imp:

**Comment by Badcholo** [comment]
I don't think it's funny to spend all that time creating a jetpack just to have it explode cause you go into a fluid of whatever type. it's like saying in vanilla minecraft to have the diamond chestplate explode and kill you if you decide to fight a Mob. I would like better protection from these such fluids.
