### ISSUE TITLE
Straightforward keymap

### ISSUE THREAD

**Issue by quentinrossetti** [Tonius/SimplyJetpacks#82]
Hi,

It would be great to have a more straightforward keymap.
- `F` Engine ON/OFF
- `G` Hover ON/OFF
- `H` Charger ON/OFF
And still have to possibility to modify those keys in the _Controls_ menu.

Really well done mod, btw !

**Comment by IdleMuse** [comment]
Seconded; this would make it much clearer how to turn on and off things with the Flux-Plated JetPack, which is currently pretty hard to figure out with rebound keys.

**Comment by Tonius** [comment]
I've separated the 'secondary' controls into their own keybinds. However they aren't in the configuration you suggested by default, because they conflict with the default keybinds of some other mods that are commonly used together with SJ.

Of course, you can still change this yourself.
