### ISSUE TITLE
TE4 Induction Smelter and Armor Plating recipies

### ISSUE THREAD

**Issue by maulkye** [Tonius/SimplyJetpacks#83]
in ModItems.java:

~ line 440:
ItemStack i = OreDictionary.getOres("ingotBronze").get(0).copy();
i.stackSize = 10;          
TERecipes.addSmelterRecipe(3200, armorPlatingTE1, i, armorPlatingTE2, null, 0);

The TE4 smelter doesn't appear to accept this combination of materials.

**Comment by maulkye** [comment]
I'm thinking TE4 (as of RC2 anyway) has changed some things or may not be done with the new smelter.  

There are other old recipes that seem not to work now (hardened glass for one).

I can't seem to find any more documentation on it yet though.

**Comment by chanzie** [comment]
same issue here as well

**Comment by KingLemming** [comment]
You have a texture pack. It isn't displaying the button on the Smelter.

**Comment by maulkye** [comment]
Wow, I never considered that.  I'll make sure to pull all my texture packs out and try it tonight after work.

**Comment by maulkye** [comment]
Yep, that was it!  The recipe works fine.  Apparently the version of Sphax for TE that I have hides the button.  Both the Tinker's Armor plates and Hardened Glass worked once I unlocked the flux slot.

Thanks for your help!
