### ISSUE TITLE
3D Model + Smart Moving Model = Models always facing south

### ISSUE THREAD

**Issue by Razorskills** [Tonius/SimplyJetpacks#84]
Hello, 

Smart Moving is one of my favourite mods, and I like to try to get support for it when there are 3D Models that normally hook to the player, but since the player model is changed to allow, laying down, crawling, superman flying etc, it has a different hook than normal minecraft.

So I am not sure what exactly it would take to allow your models to hook to the player properly when using smart moving, but this is a commit from modular power suits that fixed all the smart moving hook issues.

https://github.com/QMXTech/MachineMusePowersuits/commit/0031ba886d31b5dba93a16cbd28accbad59497a8

(It also has other fixes but it might give you an idea as to what would need to be done if you are interested in supporting an awesome mod. And perhaps asking @Korynkai for some suggestions if he is willing to since he fixed the powersuits compatibility)

If you want to try out smart moving to see what it is/ see if its worth adding support for, you need:

Smart Moving - 1.7.10 - 15.3 : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1274224
Player API - 1.7.10 - Core 1.2 : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996

For mods that hook into rendering on to the player model, there is also:
(Without this mod, Modular powersuits model would just look straight south but the player would still turn around)

Render Player API - 1.7.10 - Core 1.0 : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1283669

I really hope you could have a look at fixing this. It would make every smart moving user so happy. But yes I do know that I can disable the 3D Models, I just really do not want to since they are awesome.

**Comment by medsal15** [comment]
This is not from this mod. This is from Smart moving.

**Comment by Korynkai** [comment]
Uhh, actually I'd say it's a mod compatibility issue @medsal15, specifically with a mod that changes how movement is handled within the game. Essentially, as such, it requires a middle-man interface to any non-standard armor model in the game. This means SimplyJetpacks, Powersuits and quite a few other mods also have or have had to implement two different instances of ModelBiped, one based on ModelBiped itself for vanilla rendering and one based on ModelPlayer from PlayerAPI. The initial work on Powersuits was done by MachineMuse and I assume it was for 1.6.4. I fixed the issue once it was brought to my attention. Without these steps, there seems to be no way for SmartMoving to latch onto the model, causing some models to misbehave.... I suppose we could take it up with Divisor and see if he can find a better way, but it's not very difficult to address...

@Tonius: The files within MPS you should make note of are within src/main/scala/net/machinemuse/powersuits/client/render/item/
Specifically:
>ArmorModel.scala
ArmorModelInstance.java
SMovingArmorModel.scala
VanillaArmorModel.scala

I also added a Forge Display Exception at src/main/scala/net/machinemuse/general/gui/RenderPlayerAPIRequiredDisplayException.scala to ensure RenderPlayerAPI was loaded when Powersuits and SmartMoving were loaded together (otherwise things don't behave properly) and added to preinit like so:
>    if (ModCompatability.isSmartMovingLoaded) {
      if (!ModCompatability.isRenderPlayerAPILoaded) {
        throw new net.machinemuse.general.gui.RenderPlayerAPIRequiredDisplayException
      }
    }

Feel free to copy and augment this file if you would like a display exception in such case.

**Comment by Tonius** [comment]
Neat. Do you use the Optional annotation for this? I'd rather not ship any APIs other than the RF API.

**Comment by Korynkai** [comment]
Interestingly enough, it's more based on Loader.isModLoaded than anything and doesn't create the SmartMoving ModelBiped instance unless SmartMoving is loaded. With the proper exception handling in place, this is probably as safe, maybe even safer than Optional annotation. The SmartRender-dev and RenderPlayerAPI are required to build against, but no additional APIs are required in the released JAR. It would be up to the user to download these, however they would need the entire SmartMoving suite (optionally RenderPlayerAPI-enhancer) to use SmartMoving functionality. -- Don't get me wrong, under normal circumstances I would've used Optional annotation; however in this scenario there surprisingly was no reason to.

**Comment by Korynkai** [comment]
Actually some odd behavior has started popping up when using SM, and I suspect SimplyJetpacks and other mods that add such models now work with the newer versions of SM without modification. I've read where this may now be the case as of RPAPI 1.3 and RPAPIE and I'm noticing the PowerSuit model behaving oddly. Can somebody confirm whether or not SimplyJetpacks works properly with the latest SmartMoving? I think Tonius would prefer if he didn't have to implement this and I need to determine if it needs to be removed from PowerSuits.

On the other hand, if it doesn't work properly, this may mean much more work is in store for both of us...

**Comment by Razorskills** [comment]
Tested with:
SmartCore-1.7.10-1.0.jar
SmartMoving-1.7.10-15.3.jar
SmartRender-1.7.10-2.1.jar
PlayerAPI-1.7.10-1.2.jar
RenderPlayerAPI-1.7.10-1.3.jar

And for me the jetpacks did not hook to the player:
![2015-02-27_17 04 07](https://cloud.githubusercontent.com/assets/6126264/6422809/89fe0e90-bea2-11e4-9390-dd0ff0fa5498.png)
![2015-02-27_17 04 14](https://cloud.githubusercontent.com/assets/6126264/6422808/89fd9ca8-bea2-11e4-9c8f-f1e4401f8801.png)
![2015-02-27_17 04 19](https://cloud.githubusercontent.com/assets/6126264/6422807/89fd39ac-bea2-11e4-89e3-8c63295c7973.png)

**Comment by Korynkai** [comment]
@Razorskills and @Tonius it seems SM uses a wildcard to determine which classes SM hooks in to, perhaps we need to rename the appropriate classes to match this wildcard? I'll report back once I finish my own tests.

**Comment by Tonius** [comment]
That's... interesting. My model class names don't match with that wildcard, but it could easily be changed. I'm wondering why a check if it extends ModelBiped wouldn't be enough, though...

**Comment by Razorskills** [comment]
Well in the meantime I have been trying to disable the 3d render of the jetpacks using this:

"aesthetics settings" {
    B:"Enable Jetpack 3D Model"=false

But it just keeps showing the model

**Comment by Korynkai** [comment]
@Tonius I certainly would like to know that myself, fortunately PowerSuits' model class does in fact fall within this wildcard so I don't have to worry about it, but it doesn't change the fact that there are other mods that add armor-like models that inherit from ModelBiped without having "armor" in their name...

Also it seems I was wrong about super.render, it does need it after all...? -testing continues-

**Comment by Korynkai** [comment]
Working on another set of tests involving this, starting at baseline again (the code mentioned above) and reverting even further back essentially to how MachineMuse implemented this.... I suspect I may only need to make minor changes to MachineMuse's original code after all, however RenderPlayerAPI 1.0 broke such support requiring me to implement it differently (as seen in the current releases)...

**Comment by Korynkai** [comment]
Oy, I get it... So it seems we now need to inherit from ModelPlayerBase and RenderPlayerBase? That would mean Galacticraft's implementation is correct: https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderPlayerBaseGC.java and https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/client/model/ModelPlayerBaseGC.java

**Comment by Korynkai** [comment]
Hmm, and after all that:
Divisor:
>The best practice has not changed so far - either depend on Render Player API and let your armor model extend "api.player.model.ModelPlayer"(1.7.10) respectively "api.player.model.ModelPlayerArmor" (1.8), or create two armor model classes - one using Render Player API, one not using Render Player API - and instanciate the correct one depending on whether Render Player API is present or not.

>You should know that I recently released the mod Render Player API enhancer that enables the player to enforce a basic armor model compatibiltiy for mods that would otherwise be armor-incompatible to Smart Moving.

>The model-moving-on-the-armor-stand probem could happen in case the exact same model instance is used for the player renderer and the armor stand.

So, in other words, my current implementation is apparently proper, however something has to be done about BiblioCraft's armor instance regardless... Intriguing...

**Comment by Korynkai** [comment]
I am still working on this, trying to tackle this more from Galacticraft's direction... Seems like that may solve the instancing issue...

**Comment by Tonius** [comment]
Closing this for now. I don't use Smart Moving, so I don't have interest in adding this myself. I also don't really want to readd the flat jetpacks, because that means having unique textures for all the different use cases, which makes for ugly code as well as being annoying to manage.

If someone knows how to fix this, I'll be happy to accept a pull request.
