### ISSUE TITLE
Duplication issue when combined with Enviromine

### ISSUE THREAD

**Issue by Grim-Ascensions** [Tonius/SimplyJetpacks#89]
I'm not sure what end is causing the issue... But I figured I'd start on this end since its duplicating your mods items.

When a Camelback (from the enviromine mod) is crafted onto an armored jetpack, attempting to remove the armor plating from the jetpack will cause a duplicate jetpack and armor plate to be created. The final result is that you have 2 identical armor plates, 1 jetpack still equiped with a camelback, and 1 clone jetpack without the camelback.

My best guess is that the camelback being attached is causing recipe confusion when removing the plate. I'm not sure how the meta/dmg/RF values are handled across this issue so I can't offer more info than that.

As a note: I haven't seen this issue occur with any other armor items that a camelback is attached/removed from.

**Comment by Tonius** [comment]
Using EnviroMine 1.3.113, I can't even craft a Camelback onto a jetpack in the first place. Do I need to enable something to make that possible, or did something change?

**Comment by Grim-Ascensions** [comment]
You'll need to enable generate custom configs using Enviromine. Open enviromine's config and set these:


# Will attempt to find and generate blank configs for any custom items/blocks/etc loaded before EnviroMine. Pack developers are highly encouraged to enable this! (Resets back to false after use)
    B:"Generate Blank Configs"=true

    # Generates EnviroMines initial default files
    B:"Generate Defaults"=true


Run the game and enter into a world. This will generate enviromine's configs for all non-vanilla content. Once done, you should be able to craft the Camelback onto a jetpack.

My modpack can be found here if you prefer to pursue it that route:
http://www.technicpack.net/modpack/dangerous-depths.563211

**Comment by Tonius** [comment]
EnviroMine's crafting handler seems to be conflicting with mine here. This is an issue on their side though; they are assuming there are no shapeless recipes with a chestplate as the only ingredient. Wrong in this case, as that is exactly how removing armor from my jetpacks works.

You'll either have to disable adding camel packs to my jetpacks, or the EnviroMine authors will have to figure something out here. They're effectively messing with my recipes, and I need those recipes so jetpacks can have their armor removed.

**Comment by Grim-Ascensions** [comment]
Understood. Thanks for looking into it.
