### ISSUE TITLE
Redstone Arsenal Jetpack issue with lava

### ISSUE THREAD

**Issue by Badcholo** [Tonius/SimplyJetpacks#91]
So i use the jetpack that matches with redstone arsenal and i jump into lava. While i stay in the lava i don't take health damage and it just uses RF. The issue i have is when i leave the lava. I take damage from being on fire. Thank you for a Great Mod!

**Comment by Tonius** [comment]
This is due to the way Minecraft handles damage. Damage from being on fire is regarded as 'unblockable', but damage from lava blocks is not. The armor is less protective against 'unblockable' damage.
