### ISSUE TITLE
Ender Io Jetpack?

### ISSUE THREAD

**Issue by Badcholo** [Tonius/SimplyJetpacks#92]
Ender Io has a Armor set that uses energy and would be neat to see a jetpack for it.
Just a idea, I already use redstone arsenal and SJ together, but would be neat to see what you come up with for ender io

**Comment by Tonius** [comment]
SJ already has support for Ender IO. It can be enabled in the config. You won't be able to put a jetpack on Dark Steel armor, but there are five tiers of jetpacks that can be made with resources from Ender IO.
