### ISSUE TITLE
Feature Request: LiquidPack

### ISSUE THREAD

**Issue by Badcholo** [Tonius/SimplyJetpacks#94]
I see a Liquidpack idea that would be great if used with Redstone or Ender Io.
http://www.curse.com/mc-mods/minecraft/224371-liquipacks

**Comment by Razorskills** [comment]
perhaps using the same liquids from #80 lol

**Comment by nabijaczleweli** [comment]
@Razorskills A supercharged version of potatopack?

**Comment by Razorskills** [comment]
lol i just meant a liquid with: isFlammable

**Comment by nabijaczleweli** [comment]
@Razorskills I get it, <i>that's the joke</i>. Since jetpacks explode upon contact with flammable fluids, and this one inherently contains some, <i>it'd explode immediately</i>. Sorry, that was horrible.
