### ISSUE TITLE
Feature Request : Jetpack deactivator

### ISSUE THREAD

**Issue by Pyeroh** [Tonius/SimplyJetpacks#97]
Every jetpack of the mod can be used without limitation (except it runs on RF...), but in a security context, it could be useful to deactivate jetpacks.

Example : I'm in my base, doing stuff, when suddenly a bad guy with a jetpack enters, fly around and break my stuff !
What could've happen : the bad guy enter my base, his jetpack gets deactivated (he can't activate it anymore) because of a field he crossed, or an effect area, and when he gets out his jetpack is reactivated (so I can kick his "bottom" with a sword, like a real man :D )

Am I clear ? Or do you need further explanation ? And, what's more, is it a good suggestion ?

**Comment by Tonius** [comment]
Personally, I think this would fall outside the scope of the mod. I'd like to avoid adding features for very specific cases like this.

Have you considered building your base in a way so the bad guy can't enter to mess up stuff in the first place? Like blocking off entrances using Thaumcraft warded blocks or MFFS forcefields. Or gear up in such a way to take down intruders like this more easily (bows or other ranged weapons, maybe your own jetpack ;)  ).

Of course, the game will always have limitations in how secure a player's base can be. Especially with mods installed. There's probably more 'leaks' like this in dozens of other mods.

**Comment by Pyeroh** [comment]
I don't have Thaumcraft nor MFFS (tech-pack, and MFFS is highly unstable) but I think SecurityCraft is a good option to protect what's important.
If one day I decide to start modding, maybe an add-on to your mod could do this job =)
Thanks for your answer, and your great work
